USE [master]
GO

/****** Object:  Database [DVA]    Script Date: 11/25/2018 4:42:38 PM ******/
CREATE DATABASE [DVA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DVA', FILENAME = N'/var/opt/mssql/data/DVA.mdf' , SIZE = 4661248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DVA_log', FILENAME = N'/var/opt/mssql/data/DVA_log.ldf' , SIZE = 3416064KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DVA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DVA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DVA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DVA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DVA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DVA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DVA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DVA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DVA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DVA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DVA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DVA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DVA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DVA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DVA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DVA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DVA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DVA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DVA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DVA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DVA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DVA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DVA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DVA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DVA] SET RECOVERY FULL 
GO

ALTER DATABASE [DVA] SET  MULTI_USER 
GO

ALTER DATABASE [DVA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DVA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DVA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DVA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DVA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DVA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DVA] SET  READ_WRITE 
GO


